### ISSUE TITLE
Propose to not point people to nbviewer

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/home-assistant-notebooks#13]
Since Github renders notebooks, I don't see the point in sending people to nbviewer to view the notebooks, its just one more UI to confuse people.

**Comment by balloob** [comment]
If we can avoid it, let's not do it.

**Comment by fabaff** [comment]
With nbviewer one has the option to send the notebook to binder which allows online editing. Was useful in the past as there was no Add-on.

**Comment by balloob** [comment]
Can be closed as I don't see where this is done?
