### ISSUE TITLE
Moving docs to home-assistant.io

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/home-assistant-notebooks#6]
Hi home-assistant-notebooks maintainers,

We are about to add a new section to home-assistant.io titled "Ecosystem". It's a place where any external tools can share their documentation in an official and easy to reference capacity. I think that home-assistant-notebooks would be a great addition. The PR to add this section should be merged tonight or tomorrow and docs can start being written shortly thereafter. I don't think you would need to do anything more than taking the existing docs and splitting them up into pages for easy linking. 

Obviously you don't have to do this but we thought we'd let you know.

The PR that needs to be merged is [here](https://github.com/home-assistant/home-assistant.github.io/pull/1312).

Thanks!

**Comment by fabaff** [comment]
I guess that it would be a good idea to move the docs from https://home-assistant.io/cookbook/#jupyter-notebooks to the Ecosystem section.

**Comment by fabaff** [comment]
All there...https://home-assistant.io/docs/ecosystem/notebooks/
