### ISSUE TITLE
Update notebooks with Hass.io details

### ISSUE THREAD

**Issue by fabaff** [home-assistant/home-assistant-notebooks#8]
The notebooks were written to be uses directly beside a Home Assistant installation. With Hass.io around for quite some time I guess that people start to use the notebooks as well. To make their live easier, additional details for Hass.io should be added, e.g. path to the DB and a like.

@frenck is also working on a [Hass.io add-on](https://github.com/hassio-addons/repository-edge/tree/master/jupyter) for Jupyter Labs. And this will boost the usage even more.

**Comment by robmarkcole** [comment]
@fabaff  once the addon by @frenck is ready I will happily update the notebooks. I've also got a package which we might demo https://github.com/robmarkcole/HASS-data-detective

**Comment by balloob** [comment]
HASS Data Detective has been updated, it can now:

 - load connection string from a HASS config path
 - automatically find the HASS config path on Hass.io and if using default dir

This makes it significantly easier to share notebooks and get people started, so I want to make it a requirement for a notebook to be in the root of this repo, it should use HASS Data Detective.

### And so about how this fits in the bigger picture:

The goal is to launch https://data.home-assistant.io ([repo](https://github.com/home-assistant/data.home-assistant)) around Dec 14. The new site will guide users to install Frecks new Jupyter Lab Lite add-on and explore their own data using this repo. The add-on will have this repo pre-installed.

They should be able to open each notebook and have it run stuff on their data.

@robmarkcole is also working on a simplified Getting Started notebook that will just limit itself to be able to show information about the instance without configuration by the user, just pressing Run All should work.

**Comment by balloob** [comment]
The Jupyter Lab Lite add-on is already available in the Community Hass.io add-ons edge repo: https://github.com/hassio-addons/repository-edge
